[[protocols]]
name = "Elegoo"
protocol = "nec"
variant = "nec32"

[protocols.scancodes]
0x45 = "KEY_POWER"
0x46 = "KEY_VOLUMEUP"
0x47 = "KEY_FN_S"
0x44 = "KEY_BACK"
0x40 = "KEY_PLAYPAUSE"
0x43 = "KEY_FORWARD"
0x07 = "KEY_DOWN"
0x15 = "KEY_VOLUMEDOWN"
0x09 = "KEY_UP"
0x16 = "KEY_0"
0x19 = "KEY_EQUAL"
0x0d = "KEY_REPLY"
0x0c = "KEY_1"
0x18 = "KEY_2"
0x5e = "KEY_3"
0x08 = "KEY_4"
0x1c = "KEY_5"
0x5a = "KEY_6"
0x42 = "KEY_7"
0x52 = "KEY_8"
0x4a = "KEY_9"
